//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace MovieWeb.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CTTapPhim : DSPhimBo
    {
         dbDoAnWebEntities data = new dbDoAnWebEntities();
        public int IDPhim { get; set; }
        public Nullable<int> TapPhim { get; set; }
        public string TenPhim(int id)
        {
            string TenPhim;
            IDPhim = id;
            DSPhimBo phim = data.DSPhimBoes.Single(n => n.ID == ID);
            TenPhim = phim.TenPhim;
            return TenPhim;
        }
        public Nullable<int> ID { get; set; }
        public string Link { get; set; }
       
    }

}
