//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LichSu:DSPhimBo
    {
        dbDoAnWebEntities data = new dbDoAnWebEntities();
        public string TenDN { get; set; }
        public int IDPhim { get; set; }
        public string TenPhim(int id)
        {
            string TenPhim;
            IDPhim = id;
            DSPhimBo phim = data.DSPhimBoes.Single(n => n.ID == IDPhim);
            TenPhim = phim.TenPhim;
            return TenPhim;
        }
        public string hinh(int id)
        {
            string hinh;
            IDPhim = id;
            DSPhimBo phim = data.DSPhimBoes.Single(n => n.ID == IDPhim);
            hinh = phim.Img;
            return hinh;
        }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
